controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
# tattali_calendar:
    # resource: '@TattaliCalendarBundle/Resources/config/routing.yml'
