controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
# tattali_calendar:
    # resource: '@TattaliCalendarBundle/Resources/config/routing.yml'
rendezvous_check_availability:
  path: /rendezvous/check_availability
  methods: [POST]
  controller: App\Controller\RendezvousController::checkAvailability




