controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

afficher_carte:
    path: /carte
    controller: App\Controller\MapController::afficherCarte