controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
payment:
    path: /payment
    controller: App\Controller\PaymentController::showPaymentForm
    methods: [GET, POST]